INSERT INTO GBUS (id,name) VALUES (1,'FIRST GBU');
INSERT INTO GBUS (id,name) VALUES (2,'SECOND GBU');
INSERT INTO GBUS (id,name) VALUES (3,'THIRD GBU');
INSERT INTO GBUS (id,name) VALUES (4,'FOURTH GBU');