INSERT INTO TEAMS VALUES (1,'TEAM 1-1',1);
INSERT INTO TEAMS VALUES (2,'TEAM 1-2',1);

INSERT INTO TEAMS VALUES (3,'TEAM 2-1',2);
INSERT INTO TEAMS VALUES (4,'TEAM 2-2',2);

INSERT INTO TEAMS VALUES (5,'TEAM 3-1',3);
INSERT INTO TEAMS VALUES (6,'TEAM 3-2',3);

INSERT INTO TEAMS VALUES (7,'TEAM 4-1',4);
INSERT INTO TEAMS VALUES (8,'TEAM 4-2',4);